spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/kiran?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
welcome:
  message: I AM DEV

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/jpa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
welcome:
  message: I AM PROD

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
welcome:
  message: I AM TEST
